#ifndef MODEL_H
#define MODEL_H

// ============================================
// PosturePilot TFLite Model
// ============================================
//
// This file should be generated by scripts/train_model.py
// If you see only a single byte below, you need to:
//   1. Collect training data using MODE_COLLECT
//   2. Run: cd scripts && python train_model.py --data ./data --output ../src/model.h
//   3. Flash the firmware with the new model
//
// The placeholder below allows compilation to succeed without a trained model,
// but inference will not work until you flash a real model.
//
// Expected model format:
//   - Input:  96x96x1 grayscale, INT8 quantized
//   - Output: 2 classes (bad=0, good=1), INT8 quantized
//   - Size:   ~30-100KB depending on architecture
//
// ============================================

// Placeholder model (will be replaced by train_model.py)
alignas(16) const unsigned char posture_model[] = {
    0x00  // Placeholder - train_model.py will replace this entire array
};

const unsigned int posture_model_len = sizeof(posture_model);

#endif // MODEL_H
